server:
  port: 8082 # 配置端口号
spring:
  application:
    name: user-service # 配置服务名称
  datasource:
    url: jdbc:mysql://localhost:3306/nutrition_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true #  数据库连接地址
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    username: root # 数据库用户名
    password: 1234 # 数据库密码
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 5000
  cloud:
    nacos:
      server-addr: 192.168.200.128:8848 # Nacos服务器地址
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true # 开启请求方式前缀
  rabbitmq:
    host: 192.168.200.128  # 新虚拟机IP
    port: 5672              # AMQP端口，一般不变
    virtual-host: /          # 虚拟主机，如果你新建了 /nt，也可以改成 /nt
    username: ntadmin        # RabbitMQ用户名
    password: nt123456       # RabbitMQ密码
logging:
  level: # 日志级别
    root: info
    com.nt.tracker: debug

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
feign:
  sentinel:
    enabled: true
